# Generated by Django 4.2.5 on 2023-10-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondetails',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('FeMale', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='persondetails',
            name='mailid',
            field=models.EmailField(max_length=200),
        ),
    ]
