# Generated by Django 4.2.5 on 2023-10-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_alter_persondetails_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondetails',
            name='account_type',
            field=models.CharField(choices=[('savings account', 'savings account'), ('current account', 'current account'), ('cheque', 'cheque')], max_length=220),
        ),
        migrations.AlterField(
            model_name='persondetails',
            name='material_type',
            field=models.CharField(choices=[('debit card', 'debit card'), ('credit card', 'credit card'), ('cheque book', 'cheque book')], max_length=220, null=True),
        ),
    ]
