# Generated by Django 4.2.5 on 2023-10-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0004_alter_persondetails_material_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondetails',
            name='account_type',
            field=models.CharField(choices=[('savings account', 'savings account'), ('current account', 'current account'), ('other', 'other')], max_length=220),
        ),
    ]
